<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>GorevTakip</AssemblyName>
    <RootNamespace>GorevTakip</RootNamespace>
    <Product>ESN Görev Takip</Product>
    <Version>1.0.0</Version>
    <SatelliteResourceLanguages>tr;en</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
